# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_material_j1_manha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='j1_manha',
            new_name='j1_Matutuno',
        ),
        migrations.AddField(
            model_name='material',
            name='j1_Noturno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j1_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j2_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j2_Noturno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j2_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j3_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j3_Noturno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j3_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j4_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j4_Noturno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j4_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j5_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j5_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j6_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='material',
            name='j6_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
