# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171120_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='j1_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j1_Noturno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j1_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j2_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j2_Noturno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j2_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j3_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j3_Noturno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j3_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j4_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j4_Noturno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j4_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j5_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j5_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j6_Matutuno',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='sala',
            name='j6_Vespertino',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
