# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171120_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='j1_Matutuno',
            new_name='j1_Matutino',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='j2_Matutuno',
            new_name='j2_Matutino',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='j3_Matutuno',
            new_name='j3_Matutino',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='j4_Matutuno',
            new_name='j4_Matutino',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='j5_Matutuno',
            new_name='j5_Matutino',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='j6_Matutuno',
            new_name='j6_Matutino',
        ),
    ]
